# Generated by Django 5.0.7 on 2024-07-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='emailID',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobileNo',
            field=models.CharField(max_length=45),
        ),
    ]
