# Generated by Django 5.0.7 on 2024-07-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login_alter_register_emailid_alter_register_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mobileNo',
        ),
    ]
