# Generated by Django 5.0.7 on 2024-07-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_register_lastname_remove_register_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='emailID',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
