# Generated by Django 5.0.7 on 2024-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_login_userid_alter_register_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cookies',
            field=models.CharField(default='ABCDEFGH', max_length=100),
        ),
    ]
