# Generated by Django 5.0.7 on 2024-08-27 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_login_ipaddress_login_browsername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('alternative_phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BottomMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('length', models.FloatField()),
                ('thigh_circumference', models.FloatField()),
                ('knee_circumference', models.FloatField()),
                ('calf_circumference', models.FloatField()),
                ('ankle_circumference', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_measurements', to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TopMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_width', models.FloatField()),
                ('bust', models.FloatField()),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('armhole', models.FloatField()),
                ('sleeve_length', models.FloatField()),
                ('sleeve_circumference', models.FloatField()),
                ('top_length', models.FloatField()),
                ('neck_depth', models.FloatField()),
                ('neck_width', models.FloatField()),
                ('shoulder_to_bust', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_measurements', to='myapp.customer')),
            ],
        ),
    ]
