# Generated by Django 5.0.7 on 2024-08-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customer_bottommeasurement_topmeasurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottommeasurement',
            old_name='ankle_circumference',
            new_name='ankleCircumference',
        ),
        migrations.RenameField(
            model_name='bottommeasurement',
            old_name='calf_circumference',
            new_name='calfCircumference',
        ),
        migrations.RenameField(
            model_name='bottommeasurement',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='bottommeasurement',
            old_name='knee_circumference',
            new_name='kneeCircumference',
        ),
        migrations.RenameField(
            model_name='bottommeasurement',
            old_name='thigh_circumference',
            new_name='thighCircumference',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='alternative_phone_number',
            new_name='altPhoneNumber',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customerId',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='neck_depth',
            new_name='neckDepth',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='neck_width',
            new_name='neckWidth',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='shoulder_to_bust',
            new_name='shoulderToBust',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='shoulder_width',
            new_name='shoulderWidth',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='sleeve_circumference',
            new_name='sleeveCircumference',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='sleeve_length',
            new_name='sleeveLength',
        ),
        migrations.RenameField(
            model_name='topmeasurement',
            old_name='top_length',
            new_name='topLength',
        ),
    ]
